spring:
  datasource:
    url: jdbc:mysql://124.70.44.0:3306/permission
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 124.70.44.0
    password: 123456
    port: 6379
server:
  port: 8080